trigger:
- main

pool:
  name: Private-pool

variables:
  azureSubscription: 'e5bfadfa-1fea-4b16-8eed-6ad15cc307d3'  # The name of the service connection
  resourceGroupName: 'My-test-rg'  # Your resource group
  location: 'East US'  # Azure region
  templateFile: 'azuredeploy.json'  # Path to your ARM template file
  parametersFile: ''  # Optional, if you have a parameters file

stages:
- stage: Deploy
  jobs:
  - job: DeployResources
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        azureSubscription: $(azureSubscription)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        templateFile: $(templateFile)
        parametersFile: $(parametersFile)
